CREATE ROLE replicator WITH REPLICATION LOGIN PASSWORD 'password';
GRANT CONNECT ON DATABASE "ticketSystem" TO replicator;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES to replicator;
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO replicator;
GRANT USAGE ON SCHEMA PUBLIC TO replicator;
CREATE PUBLICATION custom_cdc FOR ALL TABLES;